---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: extmcp
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowMethods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - CONNECT
      - OPTIONS
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 0
    accessControlAllowHeaders: 
      - "*"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mcp
  namespace: extmcp
spec:
  plugin:
    mcp:
      policies:
        - match: Equals(`mcp.method`, `tools/call`) && Equals(`mcp.params.name`, `start_game`)
          action: allow
        - match: Equals(`mcp.method`, `tools/call`) && Prefix(`mcp.params.name`, `guess_number`)
          action: allow
      defaultAction: deny