image:
  registry: europe-west9-docker.pkg.dev/traefiklabs
  repository: traefik-hub/traefik-hub
  tag: "latest-v3"
  pullPolicy: Always
deployment:
  replicas: 1
ingressRoute:
  dashboard:
    enabled: false
ingressClass:
  enabled: false
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true    
logs:
  general:
    format: json
    level: DEBUG
  access:
    enabled: true
    format: json
    addInternals: false
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: keep
metrics:
  addInternals: false
  prometheus: null
  otlp:
    enabled: true
    addRoutersLabels: true
    grpc:
      enabled: true
      insecure: true
      endpoint: otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
tracing:
  addInternals: false
  otlp:
    enabled: true
    grpc:
      enabled: true
      insecure: true
      endpoint: otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
        weight: 100
resources:
  requests:
    memory: 384Mi
    cpu: 200m
  limits:
    memory: 384Mi
    cpu: 200m
ports:
  websecure:
    tls:
      enabled: true
hub:
  token: hub-license
additionalArguments:
  - --hub.platformUrl=https://api-preview.hub.traefik.io/agent
  - --hub.mcpgateway=true
  - --certificatesresolvers.le.distributedAcme=true
  - --certificatesresolvers.le.distributedAcme.storage.kubernetes=true
  - --certificatesresolvers.le.distributedAcme.email=david.blaskow@traefik.io
  - --certificatesresolvers.le.distributedAcme.tlschallenge=true
